language: android
sudo: false
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-23
    - extra-android-m2repository

before_install:
  - test "$TRAVIS_BRANCH" == "master" && sh script/decrypt_files
  - script/start_emulator.sh

after_success:
  - test "$TRAVIS_BRANCH" == "master" && ./gradlew uploadArchives